### PR TITLE
Modernize code base

### PR DESCRIPTION
**Pull request by q-b**
Use the last edition of rust available to date (2018)
Update most of the dependency.
`gpgme` was skipped since builds after `0.8.0`are broken.
`liquid` was skipped because the whole crate changed too much.

### CODE REVIEW

**Comment by Byron** [comment]
Thanks so much for the tremendous effort you inevitably put into this PR! It's absolutely welcome and very much appreciated!

I will review the changes thoroughly, merge, and create a new release soon.

As you might have noticed, I managed to disable Travis and this project is the last one that has not been migrated to github actions. That will happen today as well since it's obviously still useful for some.

**Comment by Byron** [comment]
v4.0.8 can now be found in the releases section of this repository.

**Comment by q-b** [comment]
No problem.

I tried to evaluate the use sequoia instead of gpgme. It seems feasible but the gpgme context is present everywhere. You would need to *sync* it with its equivalent from sequoia, or you would have to make a **huge** change of the whole code base.

Thank you for the release!

**Comment by Byron** [comment]
Thanks for sharing! I also took a look at sequoia, and last time I did the issue was that it won't be able to read or manipulate GPG keychains. Even though this is probably for the better, it would mean that there would have to be some sort of sequoia keychain OR share secrets safely implements key handling itself from scratch. The latter seems entirely out of scope.

Maybe I am missing something, and if so I would be glad to hear how sequoia could be used.

For me, the main benefit of doing that would be the chance to get a Windows version one day, even though that might be a feature Sequoia is not currently working on.

**Pull request merged**
